language: r
cache: packages

# ----------------+---------+-------------+
# Environment     | codecov | goodpractice|
# ----------------+---------+-------------+
# MacOS           | No      | No          |
# Linux r-devel   | Yes     | No          |
# Linux r-release | No      | Yes         |
# ----------------+---------+-------------+

matrix:
  include:
  - r: release
    os: linux
    env: 
    - INSTALL_BEAST2_NS=true
    - INSTALL_BEAST2=true
  - r: devel
    os: linux
    env: 
    - INSTALL_BEAST2=false
    - INSTALL_BEAST2_NS=false

r_github_packages:
  - ropensci/beautier@develop
  - ropensci/beastier@develop
  - jimhester/covr
  - jimhester/lintr
  - MangoTheCat/goodpractice

before_install:
  # Fix rJava error, from https://travis-ci.community/t/cannot-connect-to-java-from-r/9754/8
  - sudo $(which R) CMD javareconf
  # ImageMagick
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y libmagick++-dev; fi
  # Rmpfr
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt install -qq libmpfr-dev; fi
  # Java
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then R CMD javareconf; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then R --quiet -e 'install.packages("rJava", type="source", repos="http://cran.us.r-project.org")'; fi
  # PDF
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo tlmgr update --self; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo tlmgr install inconsolata; fi
  # libgit2-dev
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt install libgit2-dev; fi

before_script:
  # Install BEAST2. Note: beastier must work without BEAST2 installed as well
  - if [[ "$INSTALL_BEAST2" == true ]]; then Rscript -e "beastier::install_beast2()"; fi
  # Check state before mcbette is checked
  - Rscript -e "beastier::is_beast2_installed()"
  - if [[ "$INSTALL_BEAST2_NS" == true ]]; then Rscript -e 'mauricer::install_beast2_pkg("NS")'; fi
  - Rscript -e 'mauricer::is_beast2_ns_pkg_installed()'

script:
  - travis_wait 30 R CMD build .
  - travis_wait 40 R CMD check *tar.gz
  # lintr
  - if [[ "$INSTALL_BEAST2" == false ]]; then Rscript -e 'lintr::expect_lint_free()'; fi
  # Convert the paper to PDF
  - pandoc paper.md -o paper.pdf
  - if [ ! -f paper.pdf ]; then echo "file 'paper.pdf' not found" ; exit 1 ; fi

after_success:
  # Codecov
  - if [[ "$INSTALL_BEAST2_NS" == true ]]; then travis_wait 60 Rscript -e 'covr::codecov()'; fi
  # Goodpractice
  - if [[ "$INSTALL_BEAST2_NS" == true ]]; then travis_wait 60 Rscript -e 'goodpractice::gp()'; fi
  # Report
  - Rscript -e "beastier::is_beast2_installed()"
  - Rscript -e 'mauricer::is_beast2_ns_pkg_installed()'
  - Rscript -e 'remotes::install_github("ropensci/mcbette")'
  - Rscript -e 'mcbette::mcbette_report()'
  # Download thesis
  - wget https://pure.rug.nl/ws/files/132028374/Complete_thesis.pdf

after_failure:
  # Report
  - Rscript -e "beastier::is_beast2_installed()"
  - Rscript -e 'mauricer::is_beast2_ns_pkg_installed()'
  - Rscript -e 'remotes::install_github("ropensci/mcbette")'
  - Rscript -e 'mcbette::mcbette_report()'
  # Download thesis
  - wget https://pure.rug.nl/ws/files/132028374/Complete_thesis.pdf


