# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
  pull_request:
  schedule:
  - cron: "0 0 * * 6"

name: R-CMD-check

jobs:
  R-CMD-check:
    strategy:
      matrix:
        include:
          - install_beast2: "true" 
          - install_beast2: "false"

    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1

      - name: Install libmpfr-dev for Rmpfr
        run: sudo apt install -qq libmpfr-dev

      - name: Install libcurl4-openssl-dev
        run: sudo apt install -qq libcurl4-openssl-dev

      - name: Install libgit2-dev
        run: sudo apt install -qq libgit2-dev

      - name: Fix rJava error # from https://travis-ci.community/t/cannot-connect-to-java-from-r/9754/8
        run: sudo $(which R) CMD javareconf

      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
          remotes::install_cran("rcmdcheck")
          remotes::install_cran("covr")
          remotes::install_cran("lintr")
          remotes::install_github("ropensci/beautier")
          remotes::install_github("ropensci/tracerer")
          remotes::install_github("ropensci/beastier")
          remotes::install_github("ropensci/mauricer")
          remotes::install_github("ropensci/babette")
          remotes::install_github("richelbilderbeek/beastierinstall")
          remotes::install_github("MangoTheCat/goodpractice")
        shell: Rscript {0}

      - name: Install BEAST2
        env:
          INSTALL_BEAST2: ${{ matrix.install_beast2 }}
        run: if [[ "$INSTALL_BEAST2" == true ]]; then Rscript -e "beastierinstall::install_beast2()"; fi

      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}

      - name: Test coverage
        run: if [[ "$INSTALL_BEAST2" == true ]]; then Rscript -e 'covr::codecov()'; fi

      - name: Lint
        run: if [[ "$INSTALL_BEAST2" == false ]]; then Rscript -e 'lintr::lint_package()'; fi

      - name: Report
        run: beastier::beastier_report()
        shell: Rscript {0}


